package com.bancared.clase10;
import java.util.*;
import tools.jackson.databind.json.JsonMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static com.bancared.clase10.EventosModelos.*;
/** Transporte persistente de laboratorio. Se identifica como SQL, no como RabbitMQ. */
public class ColaSql implements TransporteMensajes {
    private final JdbcTemplate jdbc;private final TransactionTemplate tx;private final JsonMapper json=JsonMapper.builder().build();
    public ColaSql(JdbcTemplate j){jdbc=j;tx=new TransactionTemplate(new DataSourceTransactionManager(j.getDataSource()));j.execute("CREATE TABLE IF NOT EXISTS cola(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,payload VARCHAR(2000),estado VARCHAR(20))");}
    public boolean publicar(Evento e){jdbc.update("INSERT INTO cola(payload,estado) VALUES(?,'PENDIENTE')",json.writeValueAsString(e));return true;}
    public int consumir(int max,InboxStore inbox){int procesados=0;for(int n=0;n<max;n++){boolean uno=tx.execute(s->{var ids=jdbc.query("SELECT id FROM cola WHERE estado='PENDIENTE' ORDER BY id LIMIT 1 FOR UPDATE",(r,k)->r.getLong(1));if(ids.isEmpty())return false;long id=ids.getFirst();String payload=jdbc.queryForObject("SELECT payload FROM cola WHERE id=?",String.class,id);Evento e;try{e=json.readValue(payload,Evento.class);}catch(RuntimeException x){jdbc.update("UPDATE cola SET estado='DLQ' WHERE id=?",id);return true;}if(!PoliticaMensaje.valido(e)){jdbc.update("UPDATE cola SET estado='DLQ' WHERE id=?",id);return true;}inbox.recibir(e);jdbc.update("UPDATE cola SET estado='ACK' WHERE id=?",id);return true;});if(!uno)break;procesados++;}return procesados;}
    public void veneno(String clave){publicar(new Evento(clave,"TRANSFERENCIA_COMPLETADA","tx-veneno",100,99));}
    public List<Map<String,Object>> vista(){return jdbc.queryForList("SELECT id,payload,estado FROM cola ORDER BY id DESC LIMIT 50");}
    public String modo(){return "SQL_LOCAL";}
}
