package com.bancared.clase10;
import static com.bancared.clase10.Modelos.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;

public class TransferStore {
    private final JdbcTemplate jdbc;
    public TransferStore(JdbcTemplate jdbc){
        this.jdbc=jdbc;
        jdbc.execute("CREATE TABLE IF NOT EXISTS transferencias(id VARCHAR(80) PRIMARY KEY, command_id VARCHAR(40) UNIQUE, banco_origen VARCHAR(20), cuenta_origen VARCHAR(30), banco_destino VARCHAR(20), cuenta_destino VARCHAR(30), monto BIGINT CHECK(monto>0), descripcion VARCHAR(120), estado VARCHAR(30), detalle VARCHAR(300), reversa VARCHAR(30), liquidada BOOLEAN)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS intentos(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transfer_id VARCHAR(80), etapa VARCHAR(40), intento INTEGER, resultado VARCHAR(80))");
    }
    public Transferencia crear(SolicitudTransferencia s){
        if(s==null || s.commandId()==null || !s.commandId().matches("[A-Za-z0-9_-]{1,40}") || s.bancoOrigen()==null || s.bancoDestino()==null || !java.util.Set.of("CORDILLERA","PACIFICO").contains(s.bancoOrigen()) || !java.util.Set.of("CORDILLERA","PACIFICO").contains(s.bancoDestino()) || s.bancoOrigen().equals(s.bancoDestino()) || s.cuentaOrigen()==null || s.cuentaDestino()==null || s.monto()<=0 || s.monto()>100_000_000L || s.descripcion()==null || s.descripcion().length()>120)
            throw new ErrorNegocio("VALIDACION","Revisa clave, bancos distintos, cuentas, descripción y monto entero positivo.");
        String id="tx-"+s.commandId();
        try{jdbc.update("INSERT INTO transferencias VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",id,s.commandId(),s.bancoOrigen(),s.cuentaOrigen(),s.bancoDestino(),s.cuentaDestino(),s.monto(),s.descripcion(),"INICIADA","Esperando al Worker","SIN_SOLICITAR",false);}
        catch(DuplicateKeyException e){
            Transferencia previa=obtener(id);
            if(!previa.bancoOrigen().equals(s.bancoOrigen()) || !previa.cuentaOrigen().equals(s.cuentaOrigen()) || !previa.bancoDestino().equals(s.bancoDestino()) || !previa.cuentaDestino().equals(s.cuentaDestino()) || previa.monto()!=s.monto() || !previa.descripcion().equals(s.descripcion()))
                throw new ErrorNegocio("CLAVE_REUTILIZADA","Esta clave identifica otra solicitud.");
        }
        return obtener(id);
    }
    public Transferencia obtener(String id){
        List<Transferencia> r=jdbc.query("SELECT * FROM transferencias WHERE id=?",(s,n)->leer(s),id);
        if(r.isEmpty())throw new ErrorNegocio("TRANSFERENCIA_INEXISTENTE","Transferencia no encontrada.");
        return r.getFirst();
    }
    public List<Transferencia> todas(){return jdbc.query("SELECT * FROM transferencias ORDER BY id DESC",(r,n)->leer(r));}
    private Transferencia leer(ResultSet r)throws SQLException{return new Transferencia(r.getString("id"),r.getString("command_id"),r.getString("banco_origen"),r.getString("cuenta_origen"),r.getString("banco_destino"),r.getString("cuenta_destino"),r.getLong("monto"),r.getString("descripcion"),r.getString("estado"),r.getString("detalle"),r.getString("reversa"),r.getBoolean("liquidada"));}
    public ResultadoWorkflow terminar(String id,String estado,String detalle){jdbc.update("UPDATE transferencias SET estado=?,detalle=? WHERE id=?",estado,detalle,id);return new ResultadoWorkflow(id,estado,detalle);}
    public ResultadoWorkflow reversa(String id,String estado,String detalle){jdbc.update("UPDATE transferencias SET reversa=?,detalle=? WHERE id=?",estado,detalle,id);return new ResultadoWorkflow(id,estado,detalle);}
    public void intento(String id,String etapa,int n,String resultado){jdbc.update("INSERT INTO intentos(transfer_id,etapa,intento,resultado) VALUES(?,?,?,?)",id,etapa,n,resultado);}
    public List<Intento> intentos(){return jdbc.query("SELECT * FROM intentos ORDER BY id DESC LIMIT 60",(r,n)->new Intento(r.getString("transfer_id"),r.getString("etapa"),r.getInt("intento"),r.getString("resultado")));}
}
