services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: curso
    ports:
      - '5432:5432'


  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - '7233:7233'
      - '8233:8233'
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=usr
      - POSTGRES_PWD=pwd
      - POSTGRES_SEEDS=curso
    depends_on:
      - postgres
