spring.application.name=clase13-bancared
server.address=127.0.0.1
server.port=8080
spring.datasource.url=jdbc:h2:file:./data/portal;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.thymeleaf.cache=false
banking.role=portal
banking.bank-code=CORDILLERA
banking.service-password=${LAB_BANK_PASSWORD:curso-local}
banking.cordillera-url=http://127.0.0.1:8081
banking.pacifico-url=http://127.0.0.1:8082
banking.temporal.mode=external
banking.temporal.target=127.0.0.1:7233
banking.temporal.ui=http://localhost:8233
logging.level.io.temporal=WARN
logging.level.org.springframework.security=WARN
