spring:
  application:
    name: sigeo-clase15
  
  rabbitmq:
    host: localhost
    port: 5672
    username: sigeo
    password: sigeo_dev
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2.0

  datasource:
    url: jdbc:h2:mem:sigeodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: postgres
  
  datasource:
    url: jdbc:postgresql://localhost:5432/sigeo
    username: sigeo
    password: sigeo_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
