services:
  postgres:
    image: postgres:16-alpine
    container_name: sigeo-postgres
    environment:
      POSTGRES_DB: sigeo
      POSTGRES_USER: sigeo
      POSTGRES_PASSWORD: sigeo_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
